### ISSUE TITLE
Cannot read cookie

### ISSUE THREAD

**Issue by parkerjohn6** [yinyanfr/zerobyw-dl#23]
Always get this error:
TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]
    at ClientRequest.setHeader (node:_http_outgoing:651:3)
    at new ClientRequest (node:_http_client:291:14)
    at Object.request (node:http:100:10)
    at RedirectableRequest._performRequest (C:\Users\username\Downloads\node_modules\follow-redirects\index.js:284:24)
    at new RedirectableRequest (C:\Users\username\Downloads\node_modules\follow-redirects\index.js:66:8)
    at Object.request (C:\Users\username\Downloads\node_modules\follow-redirects\index.js:523:14)
    at dispatchHttpRequest (C:\Users\username\Downloads\node_modules\axios\dist\node\axios.cjs:2855:21)
    at C:\Users\username\Downloads\node_modules\axios\dist\node\axios.cjs:2564:5
    at new Promise (<anonymous>)
    at wrapAsync (C:\Users\username\Downloads\node_modules\axios\dist\node\axios.cjs:2544:10) {
  code: 'ERR_INVALID_CHAR'
}
No chapter is downloaded, please check the availabiliy of zerobyw or your Internet connection.
I use this [extension](https://chrome.google.com/webstore/detail/get-cookiestxt-locally/cclelndahbckbenkjhflpdbgdldlbecc) to get cookies.

**Comment by yinyanfr** [comment]
Hello, the easy way of obtaining the cookie is by opening the Network Inspector from the dev tools of your browser (normally by pressing F12).

With the Network inspector opened, refresh the page and locate the `www.zerobyw007.com` request, scroll down to the `Request Headers` section and find the `Cookie`, your cookie should look like:

```
Ckng_2132_manhuakaiguan=xxxxxxxx; Ckng_2132_saltkey=xxxxxxxx; Ckng_2132_lastvisit=xxxxxxxxx; Ckng_2132_manhua_pcadvcookie=xxxxxxxx; Ckng_2132_sid=xxxxxxxx; Ckng_2132_ulastactivity=xxxxxxxxxxxxxxxxxxxxxxxxxxx; Ckng_2132_auth=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; Ckng_2132_lastcheckfeed=xxxxxxxxxxxxxxxxxxxxxxxx; Ckng_2132_lastact=xxxxxxxxxxxxxxxxxxx
```

You can then copy and paste the cookie into a text file and pass it to the CLI by `--cookie path_to_your_cookie.txt`

**Comment by yinyanfr** [comment]
Hello @parkerjohn6 , I hope that you have found a solution to this question. As there's no update for over a week, I'm going to close this issue. Feel free to leave a comment if there's anything new.
